{
 "title": "Opentelemetry Spanmetrics Dashboard",
 "description": "Dashboard for services with OpenTelemetry instrumentation",
 "time": { "from": "2023-11-22T12:48:58.081Z", "to": "2023-11-22T15:53:47.417Z" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "staging, prod" },
   { "name": "metrics", "label": "Metrics", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info,namespace)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\"},team)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\", team=~\"$team\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Incoming Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The rate of requests handled by the app (either HTTP calls or Pubsub messages).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", namespace=~\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "The percentage of requests handled by the app that result in an error, i.e.\n- HTTP requests that return 4xx or 5xx\n- Pubsub messages that are nack-ed",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind, error_type) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])\n) \n/ on (app, namespace, team, span_name, span_kind) group_left\nsum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"}[$__rate_interval])\n)\n",
     "legendFormat": "[{{app}}] {{span_name}} => {{error_type}}"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "timeseries",
   "description": "The 95th percentile time it takes for the app to handle a request (either an HTTP call or a Pubsub message).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n    sum by (le, app, namespace, team, span_name, span_kind) (\n        rate(traces_spanmetrics_duration_bucket{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  },
  { "title": "Outgoing Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The rate of requests sent by the app (either HTTP calls, Pubsub messages, or database calls).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\", namespace=~\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "The percentage of requests sent by the app that result in an error, i.e.\n- HTTP requests that return 4xx or 5xx",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind, error_type) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])\n) \n/ on (app, namespace, team, span_name, span_kind) group_left\nsum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\"}[$__rate_interval])\n) \n",
     "legendFormat": "[{{app}}] {{span_name}} => {{error_type}}"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "timeseries",
   "description": "The 95th percentile time it takes for requests sent by the to complete (either an HTTP call, a Pubsub message, or a database call).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n    sum by (le, app, namespace, team, span_name, span_kind) (\n        rate(traces_spanmetrics_duration_bucket{app=~\"$app\", namespace=~\"$namespace\", span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  },
  { "title": "Internal Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The rate of requests handled by the app (either HTTP calls or Pubsub messages).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", span_kind=~\"SPAN_KIND_INTERNAL\", namespace=~\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "The percentage of requests handled by the app that result in an error, i.e.\n- HTTP requests that return 4xx or 5xx\n- Pubsub messages that are nack-ed",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (app, namespace, team, span_name, span_kind, error_type) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=\"SPAN_KIND_INTERNAL\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])\n) \n/ on (app, namespace, team, span_name, span_kind) group_left\nsum by (app, namespace, team, span_name, span_kind) (\n    rate(traces_spanmetrics_calls{app=~\"$app\", namespace=~\"$namespace\", span_kind=\"SPAN_KIND_INTERNAL\"}[$__rate_interval])\n)\n",
     "legendFormat": "[{{app}}] {{span_name}} => {{error_type}}"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "timeseries",
   "description": "The 95th percentile time it takes for the app to handle a request (either an HTTP call or a Pubsub message).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n    sum by (le, app, namespace, team, span_name, span_kind) (\n        rate(traces_spanmetrics_duration_bucket{app=~\"$app\", namespace=~\"$namespace\", span_kind=\"SPAN_KIND_INTERNAL\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "[{{app}}] {{span_name}}"
    }
   ]
  }
 ]
}