{
 "title": "Opentelemetry Traces Drilldown",
 "description": "Drilldown into otel traces",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "staging, prod" },
   { "name": "metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "traces", "label": "Traces", "query": "tempo" },
   { "name": "logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info,namespace)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\"},team)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\", team=~\"$team\"},app)"
    }
   },
   {
    "name": "span_name",
    "label": "Span Name",
    "query": {
     "query": "label_values(traces_spanmetrics_calls{namespace=~\"$namespace\", team=~\"$team\", app=~\"$app\"},span_name)"
    }
   },
   {
    "name": "span_kind",
    "label": "Span Kind",
    "query": {
     "query": "label_values(traces_spanmetrics_calls{namespace=~\"$namespace\", team=~\"$team\", app=~\"$app\"},span_kind)"
    }
   },
   {
    "name": "error_type",
    "label": "Error Type",
    "query": {
     "query": "label_values(traces_spanmetrics_calls{namespace=~\"$namespace\", team=~\"$team\", app=~\"$app\"},error_type)"
    }
   },
   {
    "name": "status_code",
    "label": "Span Status",
    "query": "Error : STATUS_CODE_ERROR , Unset : STATUS_CODE_UNSET , Ok : STATUS_CODE_OK"
   },
   { "name": "traceId" },
   {
    "name": "status",
    "query": {
     "query": "query_result('STATUS_CODE_ERROR=\"status=error|\", STATUS_CODE_UNSET=\"status=unset|\", STATUS_CODE_OK=\"status=ok|\"')"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result('SPAN_KIND_SERVER=\"kind=server|\",SPAN_KIND_CLIENT=\"kind=client|\", SPAN_KIND_INTERNAL=\"kind=internal|\",SPAN_KIND_CONSUMER=\"kind=consumer|\",SPAN_KIND_PUBLISHER=\"kind=publisher|\"')"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard helps you understand why specific requests went wrong.\n1. Select some filters above (if not already set)\n2. Click on a TraceId in the table below\n3. See the Trace appear below that\n4. Logs linked to that Trace appear at the bottom.\n"
   }
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Error traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.app=~\"$app\" && resource.team=~\"$team\" && resource.namespace=~\"$namespace\" && name=~\"$span_name\" && (${status:pipe}|false) && (${kind:pipe}|false) && (span.error.type=~\"$error_type\" || status!=error)} "
    }
   ]
  },
  {
   "title": "Selected Trace",
   "type": "traces",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "limit": 20, "query": "${traceId}" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=~\"$app\", namespace=~\"$namespace\"} | json | line_format `{{.body}}` | json | trace_id=~\"0*$traceId\" | line_format \"[{{.level}}] {{.message}}\""
    }
   ]
  }
 ]
}